CREATE TABLE seers_nicks_colours (
  player_uuid BINARY(16) NOT NULL,
  colour varchar(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (player_uuid)
);

CREATE TABLE seers_nicks_nicks (
  player_uuid BINARY(16) NOT NULL,
  nick varchar(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (player_uuid)
);
