discord:
  enabled: false
  channelId: changeme

join:
  chat:
    prefix: "<green>▶</green> "
    suffix: ""
  discord:
    colour: green
    prefix: ""
    suffix: ""
  messages:
  - "{player} <green>showed up. The party can finally start!</green>"
  - "{player} <green>arrived. We're back in business!</green>"
  - "{player} <green>connected. Better late than never</green>"
  - "{player} <green>is here. Great.</green>"
  - "{player} <green>is here. Let's goooo</green>"
  - "{player} <green>is here. Everybody wave!</green>"
  - "{player} <green>just joined. Brace yourselves!</green>"
  - "{player} <green>is here! Yes! Gosh</green> {player} <green>is great</green>"
  - "{player} <green>logged in. How long 'til they fall in lava?</green>"
  - "{player} <green>just logged in. Who invited the pro?</green>"
  - "{player} <green>just joined. What could possibly go wrong?</green>"

quit:
  chat:
    prefix: "<red>◀</red> "
    suffix: ""
  discord:
    colour: red
    prefix: ""
    suffix: ""
  messages:
  - "{player} <red>has left. The game just got 10% easier</red>"
  - "{player} <red>disconnected. Did they rage quit?..</red>"
  - "{player} <red>rage quit</red>"
  - "{player} <red>has left. Finally, some peace and quiet</red>"
  - "{player} <red>bailed. Guess they had better things to do</red>"
  - "{player} <red>disconnected. We’re doomed without them... or not</red>"
  - "{player} <red>logged out. Time for the real players to shine</red>"
  - "{player} <red>bailed. Did someone forget to feed them?</red>"
  - "{player} <red>is gone. Panic!</red>"
  - "{player} <red>left. Phew, the server can have a rest</red>"
  - "{player} <red>logged out. No rage quits, just graceful exits.</red>"
  - "{player} <red>vanished. And just like that, they're... gone.</red>"
  - "{player} <red>logged off. They’ve left the server, but not our hearts ❤</red>"
  - "{player} <red>disconnected. Probably to avoid another embarrassing death</red>"
  - "{player} <red>logged off. Was it something we said?</red>"
