redis:
  uri: redis://localhost:6379
  channel: seers-chat:main

discord:
  channelId: changeme

formats:
  chat:
    format: "**{display_name}** » {message}"

  emote:
    format: "_ \\* {display_name} {message}_"

  advancement:
    colour: "#FFAA00"
    # This message is currently delivered in full
    format: "{message}"

  death:
    colour: black
    # This message is currently delivered in full
    format: "{message}"

  serverStarted:
    colour: green
    format: "🟢  {server_capitalised} server has started"

  serverStopping:
    colour: red
    format: "🔴  {server_capitalised} server is stopping"
